pool:
  vmImage: 'ubuntu-18.04'

variables:

  - name: dockerFilePath
    value: 'samples/pod_identity/python/api_kv_demo//src/Dockerfile'

  - name: releaseName
    value: 'pythondemo'

  - name: chartFilePath
    value: '$(System.DefaultWorkingDirectory)/samples/pod_identity/python/api_kv_demo/chart'

  - name: acrServiceConnection
    value: 'dockersvc'

  - name: acrRepo
    value: 'pythondemo'

  - name: helmArtifactName
    value: 'pythondemochart'

  - name: kubernetesServiceConnection
    value: 'aks-sa-demo'

  - name: namespace
    value: 'demo'

  - name: host
    value: 'c2f18e30623f44dd849b.eastus2.aksapp.io'

  - name: keyValue
    value: https://aksidentitydemo.vault.azure.net/


stages:

- stage: dockerbuild
  displayName: 'Docker Build'
  jobs:
  - deployment: dockerbuild
    environment: dockerDemo
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: Docker@2
              displayName: Login to ACR
              inputs:
                command: login
                containerRegistry: $(acrServiceConnection)

            - task: Docker@2
              displayName: Build  image
              inputs:
                repository: $(acrRepo)
                command: build
                Dockerfile: $(dockerFilePath)
                containerRegistry: $(acrServiceConnection)
                tags: |
                  $(Build.BuildId)
                  $(Build.SourceVersion)

            - task: Docker@2
              displayName: Push image
              inputs:
                repository:  $(acrRepo)
                command: push
                Dockerfile: $(dockerFilePath)
                containerRegistry:  $(acrServiceConnection)
                tags: $(Build.BuildId)

            - task: Docker@2
              displayName: Logout from ACR
              condition: always()
              inputs:
                command: logout
                containerRegistry:  $(acrServiceConnection)    

            - task: PublishPipelineArtifact@1
              condition:  succeeded()
              inputs:
                targetPath: '$(chartFilePath)'
                artifact: $(helmArtifactName)
                publishLocation: 'pipeline'

- stage: deploypythonApp
  dependsOn: 'dockerbuild'
  displayName: 'Deploy Python Demo'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: helmdeploy
    environment: charpdemo
    strategy:
      runOnce:
        deploy:        
          steps:
            - download: current
              artifact: $(helmArtifactName)

            - task: HelmInstaller@0
              displayName: 'Install Helm 3.2.0'
              inputs:
                helmVersion: 3.2.0
                checkLatestHelmVersion: false      

            - task: HelmDeploy@0
              displayName: Deploy to Demo
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                namespace: $(namespace) 
                command: 'upgrade'
                chartType: 'FilePath'
                chartPath: '$(Pipeline.Workspace)/$(helmArtifactName)'
                releaseName: $(releaseName)
                install: true
                waitForExecution: false       
                arguments: '--set image.tag=$(Build.BuildId) --set ingress.host=$(host)  --set keyvault=$(keyValue) --set namespace=$(namespace) '