# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 2

image:
  name: javademo
  label: javademo
  repository: msalemaksdemoacr.azurecr.io/javademo
  pullPolicy: Always

service:
  type: ClusterIP
  name: javademo-svc
  port: 80

namespace: demo
keyvault: local


ingress:
  enabled: true
  path: javakv
  host: localhost
  tls: []

nodeSelector: {}
affinity: {}
