{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: {{ .Values.ingress.path  }}.{{ .Values.ingress.host  }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
        path: /

  {{- end }}
