# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 2

image:
  name: pythondemo
  label: pythondemo
  repository: msalemaksdemoacr.azurecr.io/pythondemo
  pullPolicy: Always

service:
  type: ClusterIP
  name: pythondemo-svc
  port: 80

namespace: demo
keyvault: local


ingress:
  enabled: true
  path: pythonkv
  host: localhost
  tls: []

nodeSelector: {}
affinity: {}
